[package]
name = "gr-provider-linux-dummy-hcd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
gr-privileged-broker = { path = "../gr-privileged-broker", version = "0.1" }
gr-realization-api = { path = "../gr-realization-api", version = "0.1" }

[lints]
workspace = true
