[package]
name = "gr-privileged-broker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
gr-controller-wire = { path = "../gr-controller-wire", version = "0.1" }
gr-dualsense-wire = { path = "../gr-dualsense-wire", version = "0.1" }
gr-realization-api = { path = "../gr-realization-api", version = "0.1" }
libc.workspace = true
thiserror.workspace = true

[lints]
workspace = true
