[package]
name = "gr-provider-linux-uinput"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
gr-realization-api = { path = "../gr-realization-api", version = "0.1" }

[lints]
workspace = true
